runtime: python37

service : default

env_variables:
  MYSQL_USER : "root"
  MYSQL_PASSWORD :  "ardaffa123"
  MYSQL_DB : "flaskapp"
  SECRET_KEY :  "bd61f3ee0f7b2621bd24db953d1d3c63"
  MYSQL_HOST: "34.101.160.253"
  MYSQL_UNIX_SOCKET : "/cloudsql/c22-ps203-capstone-352016:asia-southeast2:psycomfy-demo"