runtime: python

service : default

env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    python_version: 3.7

env_variables:
  MYSQL_USER : "root"
  MYSQL_PASSWORD :  "ardaffa123"
  MYSQL_DB : "flaskapp"
  SECRET_KEY :  "bd61f3ee0f7b2621bd24db953d1d3c63"
  MYSQL_HOST: "34.101.160.253"
  MYSQL_UNIX_SOCKET : "/cloudsql/c22-ps203-capstone-352016:asia-southeast2:psycomfy-demo"


manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20